"use strict";
(() => {
 const panel=document.createElement("details");panel.id="calibration-panel";
 panel.innerHTML=`<summary>Field-count calibration</summary><button id="back-to-zones">Back to zones</button><p>Fit SUMO demand and driver headway against edge-entry counts, then validate on separate random seeds.</p><p id="observation-window"></p><label>Observation CSV<input id="observation-file" type="file" accept=".csv,text/csv"></label><label>Counts: edge,count,begin,end<textarea id="observations" rows="6" placeholder="edge,count,begin,end"></textarea></label><label>Available vehicle edges<select id="observation-edge"></select></label><p>Use the selected edge ID in your CSV. Counts are total vehicle entries during the full observation window.</p><label>Observation source, survey date and method<textarea id="observation-source" rows="3" placeholder="Describe where these counts came from"></textarea></label><label>Observation kind<select id="observation-kind"><option value="synthetic">Synthetic / example counts</option><option value="field">Measured field counts</option></select></label><label>Demand multipliers<input id="fit-demand" value="0.75, 1, 1.25"></label><label>Headway (tau) multipliers<input id="fit-tau" value="1"></label><label>Fitting seeds<input id="fit-seeds" value="101, 102"></label><label>Validation seeds<input id="validation-seeds" value="201, 202"></label><button class="primary" id="run-calibration">Fit & validate</button><p>Uses fixed signals. At least two distinct seeds per set; no overlap. The batch runs at full speed to completion, independently of playback speed.</p><p id="calibration-progress" role="status"></p><div id="calibration-result"></div><button id="apply-calibration" hidden>Apply fitted parameters</button><p><a id="calibration-report" href="/calibration-report" target="_blank" rel="noopener" hidden>Open calibration report</a></p><a id="calibration-json" href="/calibration.json" download="calibration.json" hidden>Download calibration evidence</a>`;
 document.querySelector("aside").append(panel);let revision=-1,lastResult=null;
 function numbers(id){return $(id).value.split(/[ ,]+/).filter(Boolean).map(Number);}
 $("open-calibration").onclick=()=>{if(window.sceneEditor?.active)$("edit-city").click();panel.open=true;for(const child of panel.parentElement.children)child.hidden=child!==panel;panel.parentElement.scrollTop=0;};
 $("back-to-zones").onclick=()=>{panel.open=false;for(const child of panel.parentElement.children)child.hidden=child.id==="editor-panel";panel.parentElement.scrollTop=0;};
 $("observation-file").onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw Error("CSV must be smaller than 1 MB");$("observations").value=await file.text();}catch(error){showError(error.message);}finally{e.target.value="";}};
 $("run-calibration").onclick=()=>control("calibrate",{job:{observations:$("observations").value,source:$("observation-source").value,kind:$("observation-kind").value,demand_scales:numbers("fit-demand"),tau_scales:numbers("fit-tau"),fit_seeds:numbers("fit-seeds"),validation_seeds:numbers("validation-seeds")}});
 $("apply-calibration").onclick=()=>control("apply_calibration");
 window.calibrationUI={update(){
 const active=["calibrating","building","starting","running","paused","stopping"].includes(state.status);$("run-calibration").disabled=active||!connected;$("apply-calibration").disabled=active||!connected||state.calibration_applied;
 if(revision!==state.revision){revision=state.revision;$("observation-window").textContent=`Required observation window: ${map.begin}–${map.end} seconds. Road edits change edge IDs; update your observations after rebuilding.`;$("observation-edge").replaceChildren();const ids=[...new Set(map.roads.filter(r=>!r.pedestrian&&!r.crossing&&!r.edge?.startsWith(":" )).map(r=>r.edge))];for(const id of ids)$("observation-edge").add(new Option(id,id));}
 const p=state.calibration_progress;$("calibration-progress").textContent=p?`${p.done}/${p.total} SUMO runs completed — ${p.phase}, seed ${p.seed}`:"";
 const result=state.calibration_result;$("apply-calibration").hidden=!result;$("calibration-report").hidden=!result;$("calibration-json").hidden=!result;$("apply-calibration").textContent=state.calibration_applied?"Fitted parameters applied":"Apply fitted parameters";
 const note=document.querySelector(".note");if(note){note.querySelector("strong").textContent=state.current_calibration?.calibrated?"Field-count calibrated":"Uncalibrated experiment";note.querySelector("p").textContent=state.current_calibration?.calibrated?"GEH passed for this network and observation window. Other behaviors remain unvalidated.":"These results need matching field-count validation before they can support a real-world prediction.";}
 const signature=JSON.stringify(result);if(signature===lastResult)return;lastResult=signature;const box=$("calibration-result");box.replaceChildren();if(!result)return;
 const title=document.createElement("h3");title.textContent=result.calibration.calibrated?"Field-count GEH validation passed":"Exploratory result — uncalibrated";const summary=document.createElement("p");summary.textContent=`Best demand multiplier: ${result.parameters.demand_scale}; headway multiplier: ${result.parameters.tau_scale}. ${Math.round(result.validation.fraction_below_5*100)}% of edges have GEH < 5. Apply parameters to use this fit for new runs.`;const scope=document.createElement("p");scope.textContent=result.scope;box.append(title,summary,scope);
 const table=document.createElement("table"),head=document.createElement("tr");for(const text of ["Edge","Observed/h","Modeled/h","GEH"]){const th=document.createElement("th");th.textContent=text;head.append(th);}table.append(head);for(const [id,geh] of Object.entries(result.validation.geh)){const row=document.createElement("tr");for(const value of [id,result.validation.observed_hourly[id].toFixed(1),result.validation.modeled_hourly[id].toFixed(1),geh.toFixed(2)]){const td=document.createElement("td");td.textContent=value;row.append(td);}table.append(row);}box.append(table);
 }};
})();
